### ISSUE TITLE
Source code for generating subsampled datasets

### ISSUE THREAD

**Issue by sainyam** [nju-websoft/OpenEA#12]
Hello,

Thanks for compiling the embedding-based entity alignment methods, and for open-sourcing the GitHub repository.

I found the methods for generating subsampled version of various KG datasets to be very practical and useful. While you have publicly shared all the datasets (https://github.com/nju-websoft/OpenEA#dataset-overview), I couldn't find the source code for generating these datasets in the repo. Do you plan to share the implementation of IDS? If yes, is there an ETA?

Looking forward to your response.

Thanks,
Sainyam

**Comment by sunzequn** [comment]
Hi Sainyam,

Thanks for your interest in our work! 
Sorry that the source code of data sampling is not public now because it still needs some cleaning and refactoring work. But the coauthor has already graduated. I hereby provide the raw code for you to refer to. Hope the code can help you!

Best,
Zequn Sun
[SampKG-OpenEA.zip](https://github.com/nju-websoft/OpenEA/files/5354536/SampKG-OpenEA.zip)

**Comment by sainyam** [comment]
Thanks!

**Comment by jiaaayiii** [comment]
Hi, Sainyam, may I ask did you slove the sampling questions via the raw code? I'm working on the source code now, but have no clue.
