### ISSUE TITLE
about AttrE

### ISSUE THREAD

**Issue by nikofan18** [nju-websoft/OpenEA#8]
Hello, 

in the original paper of AttrE, is mentioned that "_The predicate alignment module merges two KGs by renaming the predicates of both KGs with a unified naming scheme ..._". Did you adopt this technique in your implementation? If yes, could you please give me the reference in your code ?

Thank you

**Comment by sunzequn** [comment]
Hi,

Thanks for your interest in our work! Our datasets and experimental setting only consider entity alignment. We do not provide relation or attribute alignment "due to the great heterogeneity between KG schemata", as we have mentioned in our paper.  Thus, our implementation of AttrE does not include the predicate alignment module.

**Comment by nikofan18** [comment]
Thank you very much for your quick response
